services:
  test:
    build: test
    image: lucas42/lucos_scheduled_scripts_test
    container_name: lucos_scheduled_scripts_test
    environment:
      - SYSTEM
      - LOGANNE_ENDPOINT
      - SCHEDULE_TRACKER_ENDPOINT
